* Added some aliases from Peepcode screencast - http://peepcode.com/products/advanced-command-line * Misc cleanup

diff --git a/bash/aliases b/bash/aliases
--- a/bash/aliases
+++ b/bash/aliases
@@ -1,14 +1,3 @@
-# changing directory to code project
-function c { cd ~/code/$1; }
-
-# alternative to "rails" command to use templates
-function railsapp {
-  template=$1
-  appname=$2
-  shift 2
-  rails $appname -m http://github.com/ryanb/rails-templates/raw/master/$template.rb $@
-}
-
 # cd
 alias ..='cd ..'
  
@@ -61,4 +50,57 @@ alias deva04='ssh csamue4916c@pacdcdtadeva04.cable.comcast.com'
 alias stgrpt01='ssh csamue4916c@pasundtastgrpt1.cable.comcast.com'
 alias prdrpt01='ssh csamue4916c@pacdcdtaprdrpt1.cable.comcast.com'
 alias greg='ssh ghenge3254c@pacdcdtaprdrpt1.cable.comcast.com'
+
+# changing directory to code project
+function c { cd ~/code/$1; }
+
+# alternative to "rails" command to use templates
+function railsapp {
+  template=$1
+  appname=$2
+  shift 2
+  rails $appname -m http://github.com/ryanb/rails-templates/raw/master/$template.rb $@
+}
+
+function take() { 
+    mkdir -p "$1"
+    cd "$1" 
+}
+
+# From http://github.com/suztomo/dotfiles
+function rmf(){
+    for file in $*
+    do
+        __rm_single_file $file
+    done
+}
+
+function __rm_single_file(){
+    if ! [ -d ~/.Trash/ ]
+    then
+        command /bin/mkdir ~/.Trash
+    fi
+
+    if ! [ $# -eq 1 ]
+    then
+        echo "__rm_single_file: 1 argument required but $# passed."
+        exit
+    fi
+
+    if [ -e $1 ]
+    then
+        BASENAME=`basename $1`
+        NAME=$BASENAME
+        COUNT=0
+        while [ -e ~/.Trash/$NAME ]
+        do
+            COUNT=$(($COUNT+1))
+            NAME="$BASENAME.$COUNT"
+        done
+
+        command /bin/mv $1 ~/.Trash/$NAME
+    else
+        echo "No such file or directory: $file"
+    fi
+}
 
